# Generated by Django 2.2.4 on 2021-05-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
