# Generated by Django 2.2.4 on 2021-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_show_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updatedate',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
    ]
