# Generated by Django 2.2.4 on 2021-05-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_show_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updatedate',
            field=models.DateTimeField(default='2020-01-01', verbose_name='2020-01-01'),
            preserve_default=False,
        ),
    ]
