# Generated by Django 2.2.4 on 2021-05-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_show_updatedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='updatedate',
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='Europe/Paris'),
            preserve_default=False,
        ),
    ]
