# Generated by Django 2.2.4 on 2021-05-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20210525_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='date',
        ),
    ]
